"use client";

import { useMemo, useState } from "react";
import { updateUserAccount } from "../database-actions";

const statusStyles = { Active:"bg-emerald-50 text-emerald-700", Pending:"bg-amber-50 text-amber-700", Suspended:"bg-red-50 text-red-700" };

export default function UsersTable({ initialData }) {
  const [users,setUsers] = useState(initialData);
  const [query,setQuery] = useState("");
  const [status,setStatus] = useState("All");
  const [userType,setUserType] = useState("All");
  const [openMenu,setOpenMenu] = useState(null);
  const [roleUser,setRoleUser] = useState(null);
  const [vipUser,setVipUser] = useState(null);
  const filtered = useMemo(() => users.filter((user) => `${user.name} ${user.phone} ${user.actualEmail ?? ""} ${user.id}`.toLowerCase().includes(query.toLowerCase()) && (status === "All" || user.status === status) && (userType === "All" || user.vipLevel > 0)), [users,query,status,userType]);

  return <div className="overflow-hidden rounded-2xl border border-[#dce8e5] bg-white shadow-[0_8px_30px_rgba(15,65,60,.04)]">
    <div className="flex flex-col gap-3 border-b border-[#e5ecea] p-5 sm:flex-row sm:justify-between"><div className="relative w-full sm:max-w-xs"><svg className="absolute top-1/2 left-3.5 h-4 w-4 -translate-y-1/2 fill-none stroke-[#80938f] stroke-2" viewBox="0 0 24 24"><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></svg><input value={query} onChange={(e) => setQuery(e.target.value)} className="h-10 w-full rounded-lg border border-[#dce6e4] bg-[#fafcfc] pr-3 pl-10 text-xs outline-none focus:border-[#2ca89c] focus:ring-3 focus:ring-[#2ca89c]/10" placeholder="Search users, phone, email or ID..." aria-label="Search users"/></div><div className="flex gap-2"><select value={userType} onChange={(e) => setUserType(e.target.value)} className="h-10 rounded-lg border border-[#dce6e4] bg-white px-3 text-xs text-[#536863]"><option value="All">All users</option><option value="VIP">VIP users</option></select><select value={status} onChange={(e) => setStatus(e.target.value)} className="h-10 rounded-lg border border-[#dce6e4] bg-white px-3 text-xs text-[#536863]"><option value="All">All statuses</option><option>Active</option><option>Pending</option><option>Suspended</option></select></div></div>
    <div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left"><thead><tr className="bg-[#f8fbfa] text-[10px] tracking-wider text-[#7b8e89] uppercase"><th className="w-12 px-5 py-3.5"><input type="checkbox" className="accent-[#087f74]" aria-label="Select all"/></th><th>User</th><th>Role</th><th>VIP</th><th>Status</th><th>Joined</th><th>Streams</th><th className="px-5 text-right">Actions</th></tr></thead><tbody className="divide-y divide-[#edf2f1]">{filtered.map((user) => <tr key={user.id} className="hover:bg-[#f9fcfb]"><td className="px-5 py-4"><input type="checkbox" className="accent-[#087f74]" aria-label={`Select ${user.name}`}/></td><td className="py-4"><div className="flex items-center gap-3"><span className={`grid h-9 w-9 place-items-center rounded-full text-[11px] font-bold ${user.color}`}>{user.initials}</span><div><p className="text-xs font-bold">{user.name}</p><p className="text-[10px] text-[#849590]">{user.email} · {user.id}</p></div></div></td><td className="py-4 text-xs text-[#526963]">{user.role}</td><td>{user.vip ? <span className="rounded-full bg-[#fff7df] px-2 py-1 text-[9px] font-bold text-[#a66b00]">VIP</span> : <span className="text-xs text-[#a1afac]">—</span>}</td><td><span className={`inline-flex items-center gap-1.5 rounded-full px-2 py-1 text-[10px] font-bold ${statusStyles[user.status]}`}><i className="h-1.5 w-1.5 rounded-full bg-current"/>{user.status}</span></td><td className="text-xs text-[#667b76]">{user.joined}</td><td className="text-xs font-semibold">{user.streams}</td><td className="relative px-5 text-right"><button onClick={() => setOpenMenu(openMenu === user.id ? null : user.id)} className="rounded-lg p-2 text-[#7d908b] hover:bg-[#edf5f3]" aria-label={`Actions for ${user.name}`}>•••</button>{openMenu === user.id && <div className="absolute top-[calc(50%+18px)] right-5 z-20 w-44 overflow-hidden rounded-xl border border-[#dce7e4] bg-white py-1.5 text-left shadow-[0_14px_35px_rgba(11,52,48,.16)]"><button onClick={() => {setRoleUser(user);setOpenMenu(null);}} className="flex w-full items-center gap-2.5 px-3.5 py-2.5 text-[11px] font-semibold text-[#405853] hover:bg-[#f2f7f6]"><span className="grid h-6 w-6 place-items-center rounded-md bg-[#e6f4f1] text-[#087f74]">R</span>Adjust role</button><button onClick={() => {setVipUser(user);setOpenMenu(null);}} className="flex w-full items-center gap-2.5 px-3.5 py-2.5 text-[11px] font-semibold text-[#405853] hover:bg-[#f2f7f6]"><span className="grid h-6 w-6 place-items-center rounded-md bg-[#fff5d9] text-[#9b6800]">★</span>Manage VIP</button></div>}</td></tr>)}</tbody></table>{!filtered.length && <div className="py-16 text-center text-sm text-[#788b87]">No users match your search.</div>}</div>
    <div className="flex items-center justify-between border-t border-[#e8efed] px-5 py-4 text-[11px] text-[#788b87]"><span>Showing {filtered.length} of 1,248 users</span><div className="flex gap-1"><button className="rounded-md border border-[#dce6e4] px-2.5 py-1.5 opacity-40">Previous</button><button className="rounded-md bg-[#087f74] px-2.5 py-1.5 font-bold text-white">1</button><button className="rounded-md px-2.5 py-1.5">2</button><button className="rounded-md border border-[#dce6e4] px-2.5 py-1.5">Next</button></div></div>
    {roleUser && <RoleModal user={roleUser} onClose={() => setRoleUser(null)} onSave={async (role,auditReason) => {await updateUserAccount(roleUser.id,{role,auditReason});setUsers((current) => current.map((user) => user.id === roleUser.id ? {...user,role} : user));setRoleUser(null);}}/>}
    {vipUser && <VipModal user={vipUser} onClose={() => setVipUser(null)} onSave={async (vipLevel,auditReason) => {await updateUserAccount(vipUser.id,{vipLevel,auditReason});setUsers((current) => current.map((user) => user.id === vipUser.id ? {...user,vipLevel,vip:vipLevel > 0} : user));setVipUser(null);}}/>}
  </div>;
}

function RoleModal({user,onClose,onSave}) {
  const [role,setRole] = useState(user.role);
  return <Modal title="Adjust user role" subtitle={`${user.name} · ${user.id}`} onClose={onClose}><form onSubmit={(e) => {e.preventDefault();const form=new FormData(e.currentTarget);onSave(role,String(form.get("reason")||""));}}><label className="mb-2 block text-xs font-bold" htmlFor="user-role">User role</label><select id="user-role" value={role} onChange={(e) => setRole(e.target.value)} className="h-11 w-full rounded-lg border border-[#dce6e4] bg-white px-3.5 text-xs outline-none focus:border-[#2ca89c]"><option>Listener</option><option>Sender</option><option>Creator</option><option>Host</option><option>Moderator</option></select><label className="mt-5 mb-2 block text-xs font-bold" htmlFor="role-reason">Reason for change</label><textarea id="role-reason" name="reason" required rows="3" placeholder="Explain why this role is being changed..." className="w-full resize-none rounded-lg border border-[#dce6e4] px-3.5 py-3 text-xs outline-none focus:border-[#2ca89c]"/><Actions onClose={onClose} confirm="Update role"/></form></Modal>;
}

function VipModal({user,onClose,onSave}) {
  const [vipLevel,setVipLevel] = useState(user.vipLevel);
  return <Modal title="Manage VIP level" subtitle={`${user.name} · ${user.id}`} onClose={onClose}><form onSubmit={(e) => {e.preventDefault();const form=new FormData(e.currentTarget);onSave(vipLevel,String(form.get("reason")||""));}}><div className="mb-5 rounded-xl bg-[#fff9e9] p-4"><p className="text-[10px] font-bold tracking-wider text-[#987022] uppercase">Current VIP status</p><p className="mt-1 text-lg font-bold text-[#79540d]">{user.vipLevel ? `VIP Level ${user.vipLevel}` : "Not a VIP user"}</p></div><label className="mb-2 block text-xs font-bold">Select VIP level</label><div className="grid grid-cols-3 gap-2">{[1,2,3,4,5].map((level) => <button key={level} type="button" onClick={() => setVipLevel(level)} className={`h-11 rounded-lg border text-xs font-bold ${vipLevel === level ? "border-amber-400 bg-amber-50 text-amber-700" : "border-[#dce6e4] text-[#687b77]"}`}>★ VIP {level}</button>)}<button type="button" onClick={() => setVipLevel(0)} className={`h-11 rounded-lg border text-xs font-bold ${vipLevel === 0 ? "border-red-300 bg-red-50 text-red-700" : "border-[#dce6e4] text-[#687b77]"}`}>Remove VIP</button></div><label className="mt-5 mb-2 block text-xs font-bold" htmlFor="vip-reason">Reason</label><textarea id="vip-reason" name="reason" required rows="3" placeholder="Explain this VIP level change..." className="w-full resize-none rounded-lg border border-[#dce6e4] px-3.5 py-3 text-xs outline-none focus:border-amber-400"/><Actions onClose={onClose} confirm="Save VIP level"/></form></Modal>;
}

function Modal({title,subtitle,onClose,children}) {
  return <div className="fixed inset-0 z-50 grid place-items-center bg-[#061c1a]/60 p-4 backdrop-blur-[2px]" role="dialog" aria-modal="true" onMouseDown={(e) => {if(e.target === e.currentTarget) onClose();}}><div className="w-full max-w-[460px] rounded-2xl bg-white shadow-[0_24px_80px_rgba(0,0,0,.25)]"><div className="flex justify-between border-b border-[#e5ecea] px-6 py-5"><div><h2 className="text-lg font-bold">{title}</h2><p className="mt-1 text-xs text-[#748782]">{subtitle}</p></div><button onClick={onClose} className="grid h-8 w-8 place-items-center rounded-lg text-xl text-[#7c8f8a] hover:bg-[#f0f5f4]" aria-label="Close modal">×</button></div><div className="p-6">{children}</div></div></div>;
}

function Actions({onClose,confirm}) {
  return <div className="mt-6 flex justify-end gap-2 border-t border-[#e8efed] pt-5"><button type="button" onClick={onClose} className="h-10 rounded-lg border border-[#d7e3e0] px-4 text-xs font-bold text-[#5d716c]">Cancel</button><button type="submit" className="h-10 rounded-lg bg-[#087f74] px-5 text-xs font-bold text-white hover:bg-[#076f66]">{confirm}</button></div>;
}
