"use client";

import { useMemo, useState } from "react";
import { useSearchParams } from "next/navigation";
import DeviceInformationTable from "../components/device-information-table";

const tabs = ["Talent List", "Verification", "Gifts Received", "Salary History", "Device Information", "Live History", "Performance", "Violations"];
export default function TalentTabs({ initialTalents, devices }) {
  const searchParams = useSearchParams();
  const requestedTab = searchParams.get("tab");
  const [active, setActive] = useState(tabs.includes(requestedTab) ? requestedTab : tabs[0]);
  return <><div className="mb-7 overflow-x-auto border-b border-[#dce7e4]" role="tablist" aria-label="Talent management sections"><div className="flex min-w-max gap-1">{tabs.map((tab) => <button key={tab} onClick={() => setActive(tab)} className={`relative px-4 py-3 text-xs font-semibold transition ${active === tab ? "text-[#087f74] after:absolute after:inset-x-0 after:bottom-0 after:h-0.5 after:bg-[#087f74]" : "text-[#71847f] hover:text-[#294a45]"}`} role="tab" aria-selected={active === tab}>{tab}</button>)}</div></div><section role="tabpanel">{active === "Talent List" ? <TalentList talents={initialTalents} /> : active === "Device Information" ? <DeviceInformationTable title="Talent Device Information" records={devices} /> : <EmptySection title={active} verification={active === "Verification"} />}</section></>;
}

function TalentList({ talents }) {
  const [query, setQuery] = useState("");
  const [typeFilter, setTypeFilter] = useState("All");
  const [statusFilter, setStatusFilter] = useState("All");
  const filtered = useMemo(() => talents.filter(([name,type,id,status]) => `${name} ${type} ${id} ${status}`.toLowerCase().includes(query.trim().toLowerCase()) && (typeFilter === "All" || type === typeFilter) && (statusFilter === "All" || status === statusFilter)), [talents,query,typeFilter,statusFilter]);
  return <><div className="mb-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[["Total talents","486","+24 this month"],["Video streamers","274","56.4% of talents"],["Audio room hosts","212","43.6% of talents"],["Awaiting verification","18","Requires review"]].map(([label,value,note]) => <div key={label} className="rounded-xl border border-[#dfe9e7] bg-white p-5"><p className="text-[11px] font-semibold text-[#768984]">{label}</p><p className="mt-2 text-2xl font-bold">{value}</p><p className="mt-2 text-[10px] text-[#429387]">{note}</p></div>)}</div>
    <div className="overflow-hidden rounded-2xl border border-[#dce8e5] bg-white"><div className="flex flex-col gap-3 border-b border-[#e5ecea] p-5 lg:flex-row lg:justify-between"><input value={query} onChange={(event) => setQuery(event.target.value)} className="h-10 w-full max-w-xs rounded-lg border border-[#dce6e4] bg-[#fafcfc] px-4 text-xs outline-none focus:border-[#2ca89c] focus:ring-3 focus:ring-[#2ca89c]/10" placeholder="Search name, ID, type or status..." aria-label="Search talents"/><div className="flex flex-col gap-2 sm:flex-row"><select value={typeFilter} onChange={(event) => setTypeFilter(event.target.value)} className="h-10 rounded-lg border border-[#dce6e4] bg-white px-3 text-xs text-[#536863]" aria-label="Filter by talent type"><option value="All">All talent types</option><option>Video Streamer</option><option>Audio Room Host</option></select><select value={statusFilter} onChange={(event) => setStatusFilter(event.target.value)} className="h-10 rounded-lg border border-[#dce6e4] bg-white px-3 text-xs text-[#536863]" aria-label="Filter by verification status"><option value="All">All verification statuses</option><option>Verified</option><option>Pending</option><option>Review</option></select></div></div>
      <div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left"><thead><tr className="bg-[#f8fbfa] text-[10px] tracking-wider text-[#7b8e89] uppercase"><th className="px-5 py-3.5">Talent</th><th>Type</th><th>Talent ID</th><th>Verification</th><th>Gifts received</th><th>Followers</th><th className="px-5 text-right">Actions</th></tr></thead><tbody className="divide-y divide-[#edf2f1]">{filtered.map(([name,type,id,status,gifts,followers]) => <tr key={id} className="text-xs hover:bg-[#f9fcfb]"><td className="px-5 py-4"><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-full bg-[#dff5f1] font-bold text-[#087f74]">{name.split(" ").map((part) => part[0]).join("")}</span><strong>{name}</strong></div></td><td className="text-[#60756f]">{type}</td><td className="font-medium text-[#60756f]">{id}</td><td><span className={`rounded-full px-2 py-1 text-[10px] font-bold ${status === "Verified" ? "bg-emerald-50 text-emerald-700" : "bg-amber-50 text-amber-700"}`}>{status}</span></td><td className="font-semibold">{gifts}</td><td>{followers}</td><td className="px-5 text-right"><button className="p-2 text-[#7d908b]" aria-label={`Actions for ${name}`}>•••</button></td></tr>)}</tbody></table>{!filtered.length && <div className="py-16 text-center text-sm text-[#788b87]">No talents match the selected filters.</div>}</div><div className="border-t border-[#e8efed] px-5 py-4 text-[10px] text-[#849691]">Showing {filtered.length} of {talents.length} sample talents</div></div></>;
}

function EmptySection({title,verification}) {
  return <div className="rounded-2xl border border-[#dce8e5] bg-white p-8 shadow-[0_8px_30px_rgba(15,65,60,.04)]"><h3 className="text-xl font-bold">{title}</h3>{verification && <p className="mt-2 max-w-2xl text-sm leading-6 text-[#71847f]">Review talent identity cards, profile images, personal details, and supporting verification documents.</p>}</div>;
}
