import Link from "next/link";
import { redirect } from "next/navigation";
import { auth, signOut } from "../../../auth";
import FeatureSearch from "../components/feature-search";

const navItems = [{ label: "Overview", href: "/home" }, { label: "Users / Senders", href: "/users" }, { label: "Talent Management", href: "/talents" }, { label: "Audit Logs", href: "/audit-logs" }, { label: "Audio rooms", href: "#" }, { label: "Reports", href: "#" }];

export default async function DashboardHome() {
  const session = await auth();
  if (!session?.user) redirect("/");
  const firstName = session.user.name?.split(" ")[0] ?? "Admin";

  return <main className="min-h-screen bg-[#f4f8f7] text-[#142c2a]">
    <aside className="fixed inset-y-0 left-0 hidden w-64 flex-col bg-[#092f2d] px-5 py-7 text-white lg:flex"><Link href="/home" className="flex items-center gap-3 px-2 text-xl font-bold"><span className="grid h-9 w-9 place-items-center rounded-xl bg-linear-to-br from-[#48e4ce] to-[#18b7a6] text-[#073d39]">▶</span>streamline</Link><nav className="mt-12 space-y-1">{navItems.map((item,index) => <Link key={item.label} href={item.href} className={`block rounded-xl px-4 py-3 text-sm ${index === 0 ? "bg-white/10 font-semibold text-[#62e0d0]" : "text-[#a9c5c1] hover:bg-white/5 hover:text-white"}`}>{item.label}</Link>)}</nav><div className="mt-auto border-t border-white/10 pt-5 text-xs text-[#82a6a1]">Streamline Admin<br/>Control center</div></aside>
    <section className="lg:pl-64">
      <header className="flex h-20 items-center gap-6 border-b border-[#dfe9e7] bg-white px-6 md:px-10"><div className="shrink-0"><p className="text-xs font-semibold tracking-widest text-[#16877d] uppercase">Admin portal</p><h1 className="text-xl font-bold">Dashboard</h1></div><FeatureSearch /><div className="ml-auto flex items-center gap-4"><div className="hidden text-right sm:block"><p className="text-sm font-semibold">{session.user.name}</p><p className="text-xs text-[#718580]">{session.user.email}</p></div><form action={async () => { "use server"; await signOut({ redirectTo: "/" }); }}><button className="rounded-lg border border-[#d7e4e1] bg-white px-4 py-2 text-xs font-semibold text-[#526b67] hover:bg-[#f1f7f5]">Sign out</button></form></div></header>
      <div className="mx-auto max-w-7xl p-6 md:p-10">
        <div className="mb-7 flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-semibold text-[#16877d]">Wednesday, July 15</p><h2 className="mt-1 text-2xl font-bold tracking-tight md:text-3xl">Good morning, {firstName}.</h2><p className="mt-1.5 text-sm text-[#71847f]">Here is what is happening across your platform today.</p></div><button className="h-10 rounded-lg border border-[#d7e4e1] bg-white px-4 text-xs font-semibold text-[#526b67] hover:bg-[#f1f7f5]">Download report</button></div>
        <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[["Total users","12,486","+12.5%","Users / Senders","/users"],["Active talents","486","+5.2%","Streamers & Hosts","/talents"],["Live now","156","+18.4%","Video & Audio","#"],["Gifts today","2.84M","+9.7%","Total gift value","/talents"]].map(([label,value,change,detail,href]) => <Link key={label} href={href} className="group rounded-xl border border-[#dfe9e7] bg-white p-5 transition hover:-translate-y-0.5 hover:border-[#aed4cf] hover:shadow-[0_10px_25px_rgba(15,65,60,.06)]"><div className="flex justify-between"><p className="text-[11px] font-semibold text-[#768984]">{label}</p><span className="rounded-full bg-emerald-50 px-2 py-1 text-[9px] font-bold text-emerald-700">{change}</span></div><p className="mt-3 text-2xl font-bold">{value}</p><div className="mt-3 flex justify-between text-[10px] text-[#879792]"><span>{detail}</span><span className="text-[#16877d] opacity-0 group-hover:opacity-100">View →</span></div></Link>)}</div>
        <div className="mt-6 grid gap-6 xl:grid-cols-[1.35fr_.65fr]">
          <section className="rounded-2xl border border-[#dce8e5] bg-white p-6 shadow-[0_8px_30px_rgba(15,65,60,.04)]"><div className="flex justify-between"><div><h3 className="text-base font-bold">Platform activity</h3><p className="mt-1 text-[11px] text-[#81928e]">Streaming activity during the last seven days</p></div><select className="h-9 rounded-lg border border-[#dce6e4] px-3 text-[10px] text-[#60736f]"><option>Last 7 days</option><option>Last 30 days</option></select></div><div className="mt-8 flex h-52 items-end justify-between gap-2 border-b border-[#e6eeec] px-2">{[42,58,51,72,65,88,79,96,73,85,68,91,76,84].map((height,index) => <div key={index} className="flex h-full flex-1 items-end"><span className="w-full rounded-t-sm bg-linear-to-t from-[#158e82] to-[#55d7c7] opacity-80" style={{height: `${height}%`}} /></div>)}</div><div className="mt-3 flex justify-between text-[9px] text-[#93a19e]"><span>Jul 9</span><span>Jul 10</span><span>Jul 11</span><span>Jul 12</span><span>Jul 13</span><span>Jul 14</span><span>Today</span></div></section>
          <section className="rounded-2xl bg-linear-to-br from-[#0a3c38] to-[#0b625a] p-6 text-white shadow-[0_12px_32px_rgba(9,73,68,.15)]"><div className="flex items-center gap-2"><span className="h-2 w-2 rounded-full bg-[#54e2cf] shadow-[0_0_0_5px_rgba(84,226,207,.12)]"/><p className="text-xs font-bold">Live network</p></div><p className="mt-2 text-[10px] text-[#88bbb5]">All systems operational</p><div className="mt-8 space-y-5">{[["Video streams","84","54%"],["Audio rooms","72","46%"],["Current audience","2,847","78%"]].map(([label,value,width]) => <div key={label}><div className="mb-2 flex justify-between text-[11px]"><span className="text-[#a8ceca]">{label}</span><strong>{value}</strong></div><div className="h-1.5 rounded-full bg-white/10"><div className="h-full rounded-full bg-[#4fdac8]" style={{width}} /></div></div>)}</div></section>
        </div>
        <div className="mt-6 grid gap-6 lg:grid-cols-2">
          <section className="overflow-hidden rounded-2xl border border-[#dce8e5] bg-white"><div className="border-b border-[#e6eeec] px-5 py-4"><h3 className="text-sm font-bold">Management</h3><p className="mt-0.5 text-[10px] text-[#849590]">Quick access to platform records</p></div><div className="divide-y divide-[#edf2f1]"><ManagementLink href="/users" title="Users / Senders" detail="Users, gifts, devices, bans, levels and history" color="bg-[#e4f6f3] text-[#087f74]"/><ManagementLink href="/talents" title="Talent Management" detail="Streamers, hosts, verification, salary and gifts" color="bg-[#fff3e4] text-[#ad6c20]"/></div></section>
          <section className="rounded-2xl border border-[#dce8e5] bg-white"><div className="flex justify-between border-b border-[#e6eeec] px-5 py-4"><div><h3 className="text-sm font-bold">Recent activity</h3><p className="mt-0.5 text-[10px] text-[#849590]">Latest platform events</p></div><button className="text-[10px] font-bold text-[#087f74]">View all</button></div><div className="divide-y divide-[#edf2f1]">{[["New talent application","Zara Ali submitted verification","4 min"],["VIP user upgraded","Olivia Martin reached VIP level 6","18 min"],["Device banned","Admin blocked device USR-1045","42 min"],["Salary processed","July host salary batch completed","1 hr"]].map(([title,detail,time]) => <div key={title} className="flex items-start gap-3 px-5 py-3.5"><span className="mt-1.5 h-2 w-2 rounded-full bg-[#38ad9f]"/><div><p className="text-[11px] font-bold">{title}</p><p className="mt-0.5 text-[10px] text-[#81928e]">{detail}</p></div><span className="ml-auto shrink-0 text-[9px] text-[#98a7a4]">{time}</span></div>)}</div></section>
        </div>
      </div>
    </section>
  </main>;
}

function ManagementLink({ href, title, detail, color }) {
  return <Link href={href} className="group flex items-center gap-4 p-5 hover:bg-[#f8fbfa]"><span className={`grid h-10 w-10 place-items-center rounded-xl text-lg font-bold ${color}`}>{title[0]}</span><div><p className="text-xs font-bold">{title}</p><p className="mt-1 text-[10px] text-[#81928e]">{detail}</p></div><span className="ml-auto text-[#78908a] transition group-hover:translate-x-1 group-hover:text-[#087f74]">→</span></Link>;
}
